version: '2.4'
services:
  meshtasticd:
    build:
      context: ./meshtasticd
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'
    volumes:
      - meshtasticd_data:/root/.portduino/default/prefs
      - meshtasticd_cfg:/etc/meshtasticd
      - meshtastic_web:/usr/share/doc/meshtasticd/web
    ports:
      - 4403:4403
      - 443:443
    restart: unless-stopped

volumes:
  meshtasticd_data:
  meshtasticd_cfg:
  meshtastic_web:
