version: '2.4'
services:
  meshtasticd:
    build:
      context: ./meshtasticd
    network_mode: host
    privileged: true
    devices:
      - "/dev/bus/usb:/dev/bus/usb" # refine to specific device as needed
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'
    volumes:
      - meshtasticd_data:/etc/meshtasticd
    group_add:
      - "plugdev"
    ports:
      - 4403:4403
      - 443:443
    restart: unless-stopped

volumes:
  meshtasticd_data:
